# Generated by Django 2.2 on 2020-07-22 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2020, 7, 22, 9, 32, 48, 632904))),
                ('body', models.TextField()),
            ],
        ),
    ]
